# Config file for [readme-md-cli](https://www.npmjs.com/package/readme-md-cli).
---
badges:
  style: flat-square
  render:
    - license
    - node.js
    - npm
    - travis-ci
see-also:
  readme-md-cli: https://www.npmjs.com/package/readme-md-cli
