---
root: true
extends: eslint:recommended
env:
  es6: true
  node: true
parserOptions:
  ecmaVersion: 9 # Same as the now deprecated 2018 option, see https://eslint.org/docs/user-guide/configuring#deprecated
rules:
  arrow-spacing: error
  block-spacing: error
  camelcase: error
  comma-dangle:
    - error
    - never
  comma-spacing:
    - error
    - after: true
      before: false
  computed-property-spacing:
    - error
    - never
  eol-last:
    - error
    - always
  eqeqeq:
    - error
    - smart
  indent:
    - error
    - 4
  key-spacing:
    - error
    - afterColon: true
      beforeColon: false
      mode: strict
  keyword-spacing: error
  linebreak-style:
    - error
    - unix
  max-len:
    - error
    - code: 120
      comments: 120
  no-console: off
  no-tabs:
    - error
    - allowIndentationTabs: false
  no-trailing-spaces: error
  no-var: error
  object-curly-spacing:
    - error
    - always
  object-property-newline:
    - error
    - allowAllPropertiesOnSameLine: true
  prefer-const:
    - error
    - destructuring: any
      ignoreReadBeforeAssign: false
  quote-props:
    - error
    - as-needed
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  semi:
    - error
    - always
  sort-keys:
    - error
    - asc
    - caseSensitive: false
      natural: true
  space-before-blocks:
    - error
    - classes: always
      functions: always
      keywords: always
  space-before-function-paren:
    - error
    - anonymous: always
      asyncArrow: always
      named: never
  space-infix-ops:
    - error
    - int32Hint: false
  space-unary-ops:
    - error
    - nonwords: false
      words: true
  spaced-comment:
    - error
    - always
  switch-colon-spacing:
    - error
    - after: true
      before: false
