language: node_js
node_js:
  - '7'
  - '8'
  - '9'
  - '10'
  - '11'
before_install: yarn global add greenkeeper-lockfile@1
install: yarn install --ignore-engines
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
