# Config file for [readme-md-cli](https://www.npmjs.com/package/readme-md-cli).
---
badges:
  style: flat-square
  license: true
  node: true
  npm: true # `vendors: []`, `list: []`, `render(ers?): []`, or `display: []`, `providers: []` instead to avoid name collisions?
see-also:
  readme-md @ npm: https://www.npmjs.com/package/readme-md
