# Config file for [readme-md-cli](https://www.npmjs.com/package/readme-md-cli).
---
badges:
  style: flat-square
  render:
    - github-actions
    - license
    - node.js
    - npm
hero-image:
  alt: readme-md Demo
  src: images/readme-md-demo.gif
see-also:
  readme-md @ npm: https://www.npmjs.com/package/readme-md
